---
- name: Deploy OpenShift Registry
  command: >
    {{ openshift.common.admin_binary }} registry
    --create --replicas={{ openshift.master.infra_nodes | length }}
    --service-account=registry {{ oreg_selector }}
    --credentials={{ openshift_master_config_dir }}/openshift-registry.kubeconfig {{ oreg_images }}
  register: oreg_results
  changed_when: "'service exists' not in oreg_results.stdout"

- name: Determine if volume is already attached to dc/docker-registry
  command: "{{ openshift.common.client_binary }} get -o template dc/docker-registry --template=\\{\\{.spec.template.spec.volumes\\}\\}"
  changed_when: false
  register: registry_volumes_output

- set_fact:
    volume_attached: "{{ registry_volume_claim in registry_volumes_output.stdout }}"

- name: Add volume to dc/docker-registry
  command: >
    {{ openshift.common.client_binary }} volume dc/docker-registry
    --add --overwrite -t persistentVolumeClaim --claim-name={{ registry_volume_claim }}
    --name=registry-storage
  when: not volume_attached | bool

# TODO: REMOVE ME
- name: debug all hostvars
  debug:
    var: hostvars[inventory_hostname]['openshift']

- include: s3.yml
  when: registry_storage_kind == 's3'
  vars:
    # TODO: default these to the cloudprovider variables if unset.
    # TODO: error out if neither is set
    aws_access_key: "{{ openshift.hosted.registry.s3.access.key }}"
    aws_secret_key: "{{ openshift.hosted.registry.s3.secret.key }}"
    aws_bucket_name: "{{ openshift.hosted.registry.s3.bucket }}"
    aws_bucket_region: "{{ openshift.hosted.registry.s3.region | default('us-east-1', true) }}"

- include: secure.yml
  when: openshift_hosted_registry_secured | bool
  vars:
    # TODO: Is this a safe assumption for a default?
    registry_hostname: "docker-registry.default.svc.cluster.local"
    # What is a more appropriate way to get these variables defined and still be a reusable role?
    openshift_generated_configs_dir: "{{ openshift.common.config_base }}/generated-configs"
    openshift_master_ca_cert: "{{ openshift.common.config_base }}/master/ca.crt"
    openshift_master_ca_key: "{{ openshift.common.config_base }}/master/ca.key"
    openshift_master_ca_serial: "{{ openshift.common.config_base }}/master/ca.serial.txt"
    registry_crt: "{{ openshift_generated_configs_dir }}/registry.crt"
    registry_key: "{{ openshift_generated_configs_dir }}/registry.key"
    registry_secret: "registry-secret"
